import type { NewProjectTemplate } from '../schema';

export const SYSTEM_TEMPLATES: NewProjectTemplate[] = [
  {
    type: 'occasion',
    name: 'Birthday Celebration',
    description: 'Plan a birthday party or celebration',
    isSystem: true,
    workspaceId: null,
    defaultFields: { recurring_annually: true, gift_budget: 0 },
    defaultTasks: [
      { title: 'Choose venue or format' },
      { title: 'Create guest list' },
      { title: 'Send invitations' },
      { title: 'Order or bake a cake' },
      { title: 'Buy gift' },
      { title: 'Plan activities' },
    ],
  },
  {
    type: 'occasion',
    name: 'Anniversary',
    description: 'Plan an anniversary celebration',
    isSystem: true,
    workspaceId: null,
    defaultFields: { recurring_annually: true },
    defaultTasks: [
      { title: 'Book restaurant or activity' },
      { title: 'Buy flowers or gift' },
      { title: 'Write card or message' },
    ],
  },
  {
    type: 'compliance',
    name: 'Resident Permit Renewal',
    description: 'Renew a resident or work permit',
    isSystem: true,
    workspaceId: null,
    defaultFields: { document_type: 'resident_permit', lead_time_days: 90 },
    defaultTasks: [
      { title: 'Check current permit expiry date' },
      { title: 'Gather required documents' },
      { title: 'Complete application form' },
      { title: 'Book appointment at immigration office' },
      { title: 'Prepare payment' },
      { title: 'Attend appointment and submit' },
      { title: 'Follow up on status' },
    ],
  },
  {
    type: 'compliance',
    name: 'Passport Renewal',
    description: 'Renew a passport',
    isSystem: true,
    workspaceId: null,
    defaultFields: { document_type: 'passport', lead_time_days: 90 },
    defaultTasks: [
      { title: 'Check passport expiry' },
      { title: 'Get passport photos taken' },
      { title: 'Fill out renewal application' },
      { title: 'Gather supporting documents' },
      { title: 'Submit application' },
      { title: 'Track delivery' },
    ],
  },
  {
    type: 'travel',
    name: 'Holiday Trip',
    description: 'Plan a holiday trip',
    isSystem: true,
    workspaceId: null,
    defaultFields: { visa_required: false },
    defaultTasks: [
      { title: 'Choose destination and dates' },
      { title: 'Check visa requirements' },
      { title: 'Book flights' },
      { title: 'Book accommodation' },
      { title: 'Arrange travel insurance' },
      { title: 'Plan activities and itinerary' },
      { title: 'Pack bags' },
      { title: 'Arrange pet/house sitter if needed' },
    ],
  },
  {
    type: 'health',
    name: 'Annual Health Checkup',
    description: 'Schedule and complete annual health screening',
    isSystem: true,
    workspaceId: null,
    defaultFields: { appointment_type: 'annual_checkup' },
    defaultTasks: [
      { title: 'Book appointment with GP' },
      { title: 'Prepare list of concerns or questions' },
      { title: 'Fast if blood test required' },
      { title: 'Attend appointment' },
      { title: 'Review results with doctor' },
      { title: 'Schedule any follow-up tests' },
    ],
  },
  {
    type: 'household',
    name: 'Deep Clean',
    description: 'Full home deep clean',
    isSystem: true,
    workspaceId: null,
    defaultFields: { frequency: 'quarterly' },
    defaultTasks: [
      { title: 'Clean kitchen appliances' },
      { title: 'Clean bathrooms thoroughly' },
      { title: 'Vacuum and mop all floors' },
      { title: 'Wipe down all surfaces' },
      { title: 'Clean windows' },
      { title: 'Wash bedding and curtains' },
    ],
  },
  {
    type: 'planning',
    name: 'Home Move',
    description: 'Plan and execute a home move',
    isSystem: true,
    workspaceId: null,
    defaultFields: {},
    defaultTasks: [
      { title: 'Find and book a removal company' },
      { title: 'Declutter and donate unused items' },
      { title: 'Notify bank and government of address change' },
      { title: 'Transfer utilities (gas, electric, water, internet)' },
      { title: 'Update home insurance' },
      { title: 'Notify friends and family of new address' },
      { title: 'Pack non-essentials' },
      { title: 'Pack essentials (moving day box)' },
      { title: 'Clean old property before handover' },
    ],
  },
];
